resolver: lts-18.28
extra-deps:
  - graphql-1.0.3.0
  - mu-graphql-0.5.0.3
  - mu-persistent-0.3.1.0
  - mu-prometheus-0.5.0.0
  - mu-rpc-0.5.0.2
  - mu-schema-0.3.1.2
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
  - stm-containers-1.1.0.4
  - stm-hamt-1.2.0.4
  - wai-middleware-prometheus-1.0.0
  - parser-combinators-1.3.0
